### ISSUE TITLE
Seleccion de colores de la página

### ISSUE THREAD

**Issue by fany2387** [mgalvaradoq/Ruedas24#1]
Se deben elegir los colores de la marca.

**Comment by mgalvaradoq** [comment]
Los colores que se seleccionaron fueron los siguientes:
- Azul claro:#00CFFA
- Fucsia: #FF0349
- Morado Oscuro: #1E1669
- Morado oscuro un poco mas claro: #241C72

<img width="1435" alt="Captura de Pantalla 2020-01-15 a la(s) 7 35 43 p  m" src="https://user-images.githubusercontent.com/48834773/73882485-ec6e9b80-4840-11ea-8ac4-f969c92c960c.png">
