### ISSUE TITLE
Definir los tipos de auto

### ISSUE THREAD

**Issue by fany2387** [mgalvaradoq/Ruedas24#11]
Definir tipos de auto y los iconos asociados a los mismos

**Comment by mgalvaradoq** [comment]
Citycar, hatchback, sedan, crossover, suv, pick-up, furgón de carga, van, híbrido

**Comment by mgalvaradoq** [comment]
Por favor agregar el link en donde esta el documento con la información.

**Comment by fany2387** [comment]
Tipos de autos
Híbrido: Colocar “ecológico” para incluir todo tipo de autos de este segmento y no solo híbridos
SUV: Contendrá también station wagon
Agregar “Convertible-coupe”
