### ISSUE TITLE
Definir todas las marcas con las que trabajaremos (todas las marcas de chile?)

### ISSUE THREAD

**Issue by mgalvaradoq** [mgalvaradoq/Ruedas24#12]
Entregable: Excel con lista de todas las marcas

**Comment by mgalvaradoq** [comment]
Por favor agregar el link en donde esta el documento con la información.

**Comment by mgalvaradoq** [comment]
@waviles2112  por favor incluye el link en donde las colocaste

**Comment by waviles2112** [comment]
https://drive.google.com/open?id=1UzfrqksuzjOSgP06QkHVMFBUfOt67h50
