### ISSUE TITLE
Creación de Logo

### ISSUE THREAD

**Issue by fany2387** [mgalvaradoq/Ruedas24#2]
En funcion de los colores y estilos conversados

**Comment by mgalvaradoq** [comment]
Se creo el logo bajo los colores definidos, prestando atención a la imagen que se quiere mostrar de Ruedas24, El logo esta en la siguiente ubicación:
https://drive.google.com/drive/folders/1BJSTaSx7qMQndedsnJb9gtW9rhBdRr8O?usp=sharing
El logo puede ser descargado:
 - Color con fondo transparente
 - Logo en horizontal y redondo
