### ISSUE TITLE
Revisión de código de webflow

### ISSUE THREAD

**Issue by mgalvaradoq** [mgalvaradoq/Ruedas24#20]
Revisar detalladamente el código que Estefany paso descargado de webflow, para verificar si funciona con la integración

**Comment by fany2387** [comment]
[ruedas24.webflowversion0.1.zip](https://github.com/mgalvaradoq/Ruedas24/files/4216967/ruedas24.webflowversion0.1.zip)

**Comment by cantwait** [comment]
Mapa de archivos principales:

css:
normalize.css 356 lineas
ruedas24.webflow.css 4973 lineas
webflow.css 1778 lineas

Archivos CSS bastante densos en contenido (va a ser tedioso leer) sin embargo a primeras de cambio se hacen CSS globales y ya...

index.html

Esta bastante entendible y a primera vista facil de transformar en componentes reutilizables, sin embargo me preocupa bastante que veo una referencia de jquery por ahi imagino que es para poder darle vida a menus, listas desplegables, etc; la cuestion es que he leido por ahi que jquery no se la lleva bien con ningun framework llamese react, vue, angular, svelte, etc.

Se ve que para mapear esto a algun framework se antoja como una tarea cuesta arriba, podemos considerar usar por ahora cualquier framework MVC o simplemente un nodejs con express.

**Comment by carlosero** [comment]
El css que genera, al menos, es reutilizable, tiene componentes comunes como blocks(columnas), grids, etc. Hay un UI funcional. El html no me parece tan loco, es una construcción con los mismos elementos del "framework" css.

@cantwait en efecto eliminando jquery y webflow.js(dependiente) ya no funcionan los menus, pero lo importante es el UI + css, no crees que podamos usarlo de esa forma?

**Comment by cantwait** [comment]
@carlosero podemos intentar dos cosas:

- usamos el código generado tal cual y lo montamos en un Adonisjs
- Nos montamos en ese reto y lo intentamos de buenas a primera con nuxtjs.

Cómo yo lo veo montarlo en Adonisjs nos permitiría interactuar lo mínimo con HTML y css y nos enfocamos en la construcción de backend directamente, podríamos hasta considerar construirlo sobre un MySQL.

Nos daría oportunidad de salir más rápido, eso sí, los portales administrativos si los haríamos en un SPA usando vuejs svelte, o cualquier otro framework.

Ventaja: Adonisjs es una copia de Laravel (PHP) o Rails, pero en javascript (nodejs) es una fortaleza ya que es el típico MVC.

Desventaja: hay que usar redis para poder escalar de forma horizontal lo que conlleva aumento del budget ya que seria: MySQL, Google RUN (basado en Docker), redis y algolia (para indexar data), y por otro lado, construyendo los portales administrativos (digo portales porque no estoy seguro cuántos van a ser todavía), se meten en un S3 o algo así.

Lo otro es bueno darnos golpes con Nuxtjs de buenas a primeras y ver que tan rápido podemos ir.

**Comment by cantwait** [comment]
@mgalvaradoq @fany2387  @carlosero  hice un commit del UI montado en adonisjs.

**Comment by cantwait** [comment]
Por ahora adonis esta funcionando como un silvestre contenedor web donde solamente montamos los recursos de webflow que @fany2387 generó.

Lo otro que estoy pensando es donde poder desplegar la pagina: mis opciones por ahora son:

- AWS Elastic Beanstalk 

- Google Cloud Run <-- este a pesar de pintar como el mas barato y conveniente es un stateless docker container lo que implicaria tener un redis desde el principio ya que esta vaina te cobra por procesamiento entonces si el pana ve que nadie envia peticiones entonces se duerme lo que siginifica que se perderia session...

- Google AppEngine Flex

- Heroku ??? (Todavia consideriariamos esto??)

**Comment by cantwait** [comment]
Nota: Obviamente podemos considerar tener el app en nuestros locals hasta que necesitemos realmente desplegarlo, metemos en un docker compose para que cada quien pueda ejecutar en su ambiente local sin problema

**Comment by carlosero** [comment]
@cantwait nice, ya lo tengo corriendo local, all good. Definiendo los contenedores lo podemos tener en heroku gratuito como ambiente de pruebas mientras esta en dev (o algún otro que conozcas que podamos usar alguna especie de capa free o very cheap donde lo podamos tener mientras esta en dev). Para prod pienso que puede ser AWS. Creo que podemos dar este issue por cerrado y abrir otro para discuss next steps. Creé este: #29
